name: OWASP Dependency-Check 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      # Cache do OWASP Dependency-Check
      - name: Cache do OWASP Dependency-Check
        uses: actions/cache@v3
        with:
          path: dependency-check/
          key: ${{ runner.os }}-dependency-check-${{ hashFiles('**/dependency-check-*.zip') }}
          restore-keys: |
            ${{ runner.os }}-dependency-check

      # Cache do Gradle
      - name: Cache do OWASP Dependency-Check (Gradle)
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-dependency-check-gradle
          restore-keys: |
            ${{ runner.os }}-dependency-check-gradle

      # Checkout código
      - name: Checkout código
        uses: actions/checkout@v4

      # Configurar Java 17
      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Baixar e instalar a versão mais recente do OWASP Dependency-Check, se necessário
      - name: Baixar e instalar a versão mais recente do OWASP Dependency-Check
        run: |
          DEPENDENCY_CHECK_VERSION=$(curl -s https://api.github.com/repos/jeremylong/DependencyCheck/releases/latest | jq -r '.tag_name' | sed 's/v//')
          if [ -z "$DEPENDENCY_CHECK_VERSION" ]; then
            echo "❌ Falha ao obter a versão mais recente do Dependency-Check."
            exit 1
          fi
          wget https://github.com/jeremylong/DependencyCheck/releases/download/v${DEPENDENCY_CHECK_VERSION}/dependency-check-${DEPENDENCY_CHECK_VERSION}-release.zip
          unzip dependency-check-${DEPENDENCY_CHECK_VERSION}-release.zip

      # Rodar o OWASP Dependency-Check
      - name: Rodar OWASP Dependency-Check
        run: |
          export SUPPRESS_LOGGING=true
          dependency-check/bin/dependency-check.sh --scan . --format HTML --out reports --noupdate || echo "⚠️ Dependency-Check falhou, mas o pipeline continuará..."

