name: OWASP Dependency-Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - name: Cache do OWASP Dependency-Check Database
        uses: actions/cache@v3
        with:
          path: ~/.dependency-check/data
          key: ${{ runner.os }}-dependency-check-db
          restore-keys: |
            ${{ runner.os }}-dependency-check-db

      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Baixar e instalar a versão mais recente do OWASP Dependency-Check
        run: |
          DEPENDENCY_CHECK_VERSION=$(curl -s https://api.github.com/repos/jeremylong/DependencyCheck/releases/latest | jq -r '.tag_name' | sed 's/v//')
          if [ -z "$DEPENDENCY_CHECK_VERSION" ]; then
            echo "❌ Falha ao obter a versão mais recente do Dependency-Check."
            exit 1
          fi
          wget https://github.com/jeremylong/DependencyCheck/releases/download/v${DEPENDENCY_CHECK_VERSION}/dependency-check-${DEPENDENCY_CHECK_VERSION}-release.zip
          unzip dependency-check-${DEPENDENCY_CHECK_VERSION}-release.zip
          export SUPPRESS_LOGGING=true
          export JAVA_OPTS="-Xmx2G"
          dependency-check/bin/dependency-check.sh --scan . --format HTML --out reports || echo "⚠️ Dependency-Check falhou, mas o pipeline continuará..."
